### ISSUE TITLE
ValueError: not enough values to unpack (expected at least 2, got 1)

### ISSUE THREAD

**Issue by louishot** [gbstack/ffprobe-python#1]
```
Traceback (most recent call last):
  File "U:/git/Documents/ts_download/test4.py", line 5, in get_video_info
    metadata = FFProbe(file)
not enough values to unpack (expected at least 2, got 1)
  File "C:\Python\Python38-32\lib\site-packages\ffprobe\ffprobe.py", line 54, in __init__
    self.streams.append(FFStream(data_lines))
False
  File "C:\Python\Python38-32\lib\site-packages\ffprobe\ffprobe.py", line 114, in __init__
    self.__dict__.update({key: value for key, value, *_ in [line.strip().split('=')]})
  File "C:\Python\Python38-32\lib\site-packages\ffprobe\ffprobe.py", line 114, in <dictcomp>
    self.__dict__.update({key: value for key, value, *_ in [line.strip().split('=')]})
ValueError: not enough values to unpack (expected at least 2, got 1)
```

```
ffprobe -v error -show_streams -print_format json media\demo\The.Elephant.Queen.2019.1080p_de.mp4
{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_time_base": "6211676/297862611",
            "codec_tag_string": "avc1",
            "codec_tag": "0x31637661",
            "width": 1920,
            "height": 1038,
            "coded_width": 1920,
            "coded_height": 1040,
            "has_b_frames": 1,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "320:173",
            "pix_fmt": "yuv420p",
            "level": 40,
            "color_range": "tv",
            "color_space": "bt709",
            "color_transfer": "bt709",
            "color_primaries": "bt709",
            "chroma_location": "topleft",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "24000/1001",
            "avg_frame_rate": "2139968000/89254491",
            "time_base": "1/16000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 89212256,
            "duration": "5575.766000",
            "bit_rate": "9878894",
            "bits_per_raw_sample": "8",
            "nb_frames": "133748",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "handler_name": "VideoHandler"
            }
        },
        {
            "index": 1,
            "codec_name": "ac3",
            "codec_long_name": "ATSC A/52A (AC-3)",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "ac-3",
            "codec_tag": "0x332d6361",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 6,
            "channel_layout": "5.1(side)",
            "bits_per_sample": 0,
            "dmix_mode": "-1",
            "ltrt_cmixlev": "-1.000000",
            "ltrt_surmixlev": "-1.000000",
            "loro_cmixlev": "-1.000000",
            "loro_surmixlev": "-1.000000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/48000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 267638784,
            "duration": "5575.808000",
            "bit_rate": "384000",
            "nb_frames": "174326",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "handler_name": "SoundHandler"
            },
            "side_data_list": [
                {
                    "side_data_type": "Audio Service Type"
                }
            ]
        }
    ]
}

```

**Comment by louishot** [comment]
there is another way I can use os.popen with ffprobe, should be better to detect a video information without a third-party modules required

**Comment by Frono** [comment]
I had this same issue. The problem was that the code does not trap for errors when parsing the ffprobe results. If the file has [SIDE_DATA] the code fails at line 112 because it cannot parse the text using an '=' delimiter when the text has no '=' sign.

I'm not very familiar with python, so I just forced it to ignore everything between [SIDE_DATA] and [/SIDE_DATA].

**Comment by M3dinar** [comment]
#3 I made the following pull request with the fix.
